// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AOCS_RTP;

/************************************************************/
/**
 * 
 */
public class AOCS_Configuration {
	/**
	 * 
	 */
	public boolean ACON_pollSkedFlag = false;
	/**
	 * 
	 */
	public int[] ACON_aocsRate;
	/**
	 * Store the right configuration SKED to run for each mode during the mode transition (config step)
	 */
	public String[] ACON_SKEDFilenumber;

	/**
	 * Starts the configuration sked
	 * @param modeID 
	 * @return 
	 */
	public AOCS_RTP.AOCS_Shell.GDEF_STATUS ACON_StartSked(int modeID) {
		/*
		* Choose the right SKED to run
		*/
		String active_fileNumber = ACON_SKEDFilenumber[modeID];
		/* read the sked file and start execution*/
		//sked_started = SXAP_ExecuteSkedFileNumber(active_fileNumber, SXAP_BIG_ENDIAN);
		/* RETURN */
		return AOCS_Shell.GDEF_STATUS.GDEF_SUCCESS;
	}

	/**
	 *  Rountine to determine the current ACON Configuration Sked status.
	 * @return 
	 */
	public boolean ACON_GetSkedStatus() {
		return ACON_pollSkedFlag;
	}

	/**
	 * Stes the rate for the given mode
	 * @param modeID 
	 */
	public void ACON_SetRate(int modeID) {
		/* update the rate according to the current mode */
		AOCS_Shell.aocs_State_Machine.AOCS_SetPeriod(ACON_aocsRate[modeID]);
	}
}
