// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AOCS_RTP;

/************************************************************/
/**
 * 
 */
public interface AocsShellEventHandler {
	/**
	 * Define event handler functions 222
	 */
	public void handleEvent();
}
