// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AOCS_RTP;

/************************************************************/
/**
 * 
 */
public class Increment {
	/**
	 * 
	 */
	private int counter;

	/**
	 * 
	 */
	public void increment() {
	}

	/**
	 * 
	 * @return 
	 */
	public Increment() {
	}
}
