// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AOCS_RTP;

import java.util.Queue;

/************************************************************/
/**
 * 
 */
public class CAN_Node {
	/**
	 * 
	 */
	public Integer Node_Address = 255;
	/**
	 * 
	 */
	public Queue CAN_Buffer;

	/**
	 * send tc de destinartion node
	 * @param destination send tc de destinartion node
	 */
	public void CAN_send_tc(int destination) {
	}

	/**
	 * send solicited TM
	 * @param destination 
	 */
	public void CAN_send_tm(int destination) {
	}
}
