// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AOCS_RTP;

import java.util.List;
import java.util.concurrent.Semaphore;

// Manual imports
import java.lang.Thread;
// End of manual imports

/************************************************************/
/**
 * 
 */
public class StateThread extends Thread {
	/**
	 * 
	 */
	private List pipeInputStream;
	/**
	 * 
	 */
	public static Semaphore lock;
}
