// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package AOCS_RTP;

import AOCS_RTP.AOCS_State_Machine.AOCS_shell_configuration;

/************************************************************/
/**
 * 
 */
public interface AOCS_Shell_EventHandler {
	/**
	 * Define event handler functions
	  * sould be like this but the code generator wont allow it hence the nocode gen flag
	  * I'm generationg the ocde, adding the nocodegen profile then modify the code manually
	  * int handleEvent(AOCS_shell_configuration config);
	 */
	int handleEvent(AOCS_shell_configuration config);
}
